apiVersion: v1
kind: Secret
metadata:
  name: buildservice-add-rust-buildpack
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: "tap-overlays"
type: Opaque
stringData:
  buildservice-add-rust-buildpack.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"metadata":{"name":"dependency-updater"}, "kind": "TanzuNetDependencyUpdater"})
    ---
    spec:
      inlineDescriptor:
        clusterStores:
        #@overlay/match by="name", missing_ok=True
        - name: default
          sources:
          #@overlay/append
          - image: docker.io/paketocommunity/rust:0.21.0
        clusterBuilders:
        #@overlay/match by="name", missing_ok=True
        - name: base
          order:
          #@overlay/append
          - group:
            - id: paketo-community/rust
        #@overlay/match by="name", missing_ok=True
        - name: base-jammy
          order:
          #@overlay/append
          - group:
            - id: paketo-community/rust