#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: tap-install
type: kubernetes.io/dockerconfigjson
stringData:
  #@yaml/text-templated-strings
  .dockerconfigjson: |-
    {
      "auths": {
        "(@= data.values.image_registry.project_path.split('/')[0] @)": {
          "username": "(@= data.values.image_registry.username @)",
          "password": "(@= data.values.image_registry.password @)"
        }
      }
    }
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: registry-credentials
  namespace: tap-install
spec:
  toNamespaces:
  - '*'